@basedUrl = http://localhost:3000

### Read all films
GET {{basedUrl}}/films

### Read a single film
GET {{basedUrl}}/films/2

### Read all films with duration upper or equal than 120
GET {{basedUrl}}/films?minimum-duration=120

### Create a new film
POST {{basedUrl}}/films
Content-Type: application/json

{
    "title": "The Lord of the Rings",
    "director": "Peter Jackson",
    "duration": 178,
    "budget": 93000000
}